<?php
include_once('circle.php');

class cylinder extends circle
{
    public $height;

    public function __construct($name, $radius, $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }

    public function calculateArea()
    {
        return parent::calculateArea() * 2 + parent::calcullatePerimeter() * $this->height; // TODO: Change the autogenerated stub
    }

    public function calculateVolume()
    {
        return parent::calculateArea() * $this->height; // TODO: Change the autogenerated stub
    }
}

?>